name: Pull Request Trigger
on:
  pull_request:
    types: [opened, closed, reopened]
    branches: [main]
    
jobs:
  createCard:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'reopened'}}
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Project Board
          column-name: PR Needs review
          issue-number: ${{ github.event.number }}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Check output
        run: echo ${{ steps.coupc.outputs.card-id }}
      
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          message: 'Error! Cannot find a linked issue associated with this PR, Please link your issue by adding Fixes #<issue number goes here>'

     